-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.api_pricing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  api_provider text NOT NULL CHECK (api_provider = ANY (ARRAY['openai'::text, 'perplexity'::text, 'serpapi'::text, 'twitter'::text, 'reddit'::text])),
  model_name text NOT NULL,
  service_type text,
  cost_per_1k_input_tokens numeric,
  cost_per_1k_output_tokens numeric,
  cost_per_request numeric,
  effective_from timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_pricing_pkey PRIMARY KEY (id)
);
CREATE TABLE public.api_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  api_provider text NOT NULL CHECK (api_provider = ANY (ARRAY['openai'::text, 'perplexity'::text, 'serpapi'::text, 'twitter'::text, 'reddit'::text])),
  api_endpoint text NOT NULL,
  model_name text,
  total_tokens integer DEFAULT 0,
  request_tokens integer DEFAULT 0,
  response_tokens integer DEFAULT 0,
  estimated_cost numeric DEFAULT 0.0,
  platform text CHECK (platform = ANY (ARRAY['twitter'::text, 'reddit'::text, 'gmail'::text, 'telegram'::text, 'system'::text, 'knowledge_base'::text, 'sociomemory'::text])),
  operation text,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT api_usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.chat_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  chat_id bigint NOT NULL,
  platform text NOT NULL,
  style_mode text DEFAULT 'default'::text,
  constraints jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  response_style text DEFAULT 'default'::text,
  use_knowledge_base boolean DEFAULT true,
  use_perplexity boolean DEFAULT true,
  use_perplexity_for_low_confidence boolean DEFAULT false,
  search_enabled boolean DEFAULT true,
  CONSTRAINT chat_configs_pkey PRIMARY KEY (id),
  CONSTRAINT chat_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.context_references (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  message_id uuid,
  context_type text NOT NULL,
  context_id text NOT NULL,
  relevance_score double precision DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT context_references_pkey PRIMARY KEY (id),
  CONSTRAINT context_references_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.context_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  setting_key character varying NOT NULL UNIQUE,
  setting_value integer NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT context_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.elite_waitlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  user_id uuid,
  status character varying DEFAULT 'pending'::character varying,
  company_name character varying,
  use_case text,
  current_tier character varying,
  monthly_usage numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  contacted_at timestamp with time zone,
  notes text,
  CONSTRAINT elite_waitlist_pkey PRIMARY KEY (id),
  CONSTRAINT elite_waitlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.entities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  entity_type character varying NOT NULL,
  embedding USER-DEFINED,
  extra_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.entity_mentions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_id uuid NOT NULL,
  memory_id uuid NOT NULL,
  mention_context text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT entity_mentions_pkey PRIMARY KEY (id),
  CONSTRAINT entity_mentions_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id),
  CONSTRAINT entity_mentions_memory_id_fkey FOREIGN KEY (memory_id) REFERENCES public.memories(id)
);
CREATE TABLE public.escalations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform text NOT NULL,
  message_id text,
  chat_id text,
  original_message text NOT NULL,
  suggested_reply text,
  confidence_score double precision,
  reason text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'edited'::text])),
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  resolved_by text,
  metadata jsonb DEFAULT '{}'::jsonb,
  confidence double precision DEFAULT 0.0,
  user_rating text CHECK (user_rating = ANY (ARRAY['good'::text, 'bad'::text])),
  rated_at timestamp with time zone,
  response_embedding USER-DEFINED,
  CONSTRAINT escalations_pkey PRIMARY KEY (id),
  CONSTRAINT escalations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.extended_context_cache (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  platform character varying NOT NULL,
  source_id character varying NOT NULL,
  query_text text NOT NULL,
  context_data jsonb NOT NULL,
  token_count integer NOT NULL,
  search_attempts integer DEFAULT 1,
  relevance_score double precision,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT extended_context_cache_pkey PRIMARY KEY (id),
  CONSTRAINT extended_context_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.github_commits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  repo_id uuid,
  commit_sha text NOT NULL,
  message text NOT NULL,
  author text NOT NULL,
  committed_at timestamp with time zone NOT NULL,
  branch text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT github_commits_pkey PRIMARY KEY (id),
  CONSTRAINT github_commits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT github_commits_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES public.github_repositories(id)
);
CREATE TABLE public.github_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  auto_sync_commits boolean DEFAULT true,
  sync_private_repos boolean DEFAULT true,
  enable_showcase boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  access_token text,
  CONSTRAINT github_configs_pkey PRIMARY KEY (id),
  CONSTRAINT github_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.github_pull_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  repo_id uuid,
  pr_number integer NOT NULL,
  title text NOT NULL,
  state text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  merged_at timestamp with time zone,
  CONSTRAINT github_pull_requests_pkey PRIMARY KEY (id),
  CONSTRAINT github_pull_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT github_pull_requests_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES public.github_repositories(id)
);
CREATE TABLE public.github_pushes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  repo_id uuid NOT NULL,
  push_id text NOT NULL,
  ref text NOT NULL,
  branch text,
  before_sha text,
  after_sha text NOT NULL,
  commit_count integer DEFAULT 0,
  commits jsonb,
  pusher_name text,
  pusher_email text,
  pushed_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT github_pushes_pkey PRIMARY KEY (id),
  CONSTRAINT github_pushes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(user_id)
);
CREATE TABLE public.github_repo_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  repo_id uuid,
  file_path text NOT NULL,
  file_content text,
  language text,
  size integer,
  last_commit_sha text,
  synced_at timestamp with time zone DEFAULT now(),
  CONSTRAINT github_repo_files_pkey PRIMARY KEY (id),
  CONSTRAINT github_repo_files_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES public.github_repositories(id)
);
CREATE TABLE public.github_repositories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  repo_id text NOT NULL,
  repo_name text NOT NULL,
  repo_full_name text NOT NULL,
  description text,
  is_private boolean DEFAULT false,
  last_push_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  private boolean,
  default_branch text,
  language text,
  stargazers_count integer DEFAULT 0,
  watchers_count integer DEFAULT 0,
  forks_count integer DEFAULT 0,
  open_issues_count integer DEFAULT 0,
  pushed_at timestamp with time zone,
  last_synced_at timestamp with time zone,
  readme_content text,
  languages jsonb DEFAULT '{}'::jsonb,
  topics ARRAY DEFAULT '{}'::text[],
  stars integer DEFAULT 0,
  CONSTRAINT github_repositories_pkey PRIMARY KEY (id),
  CONSTRAINT github_repositories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.github_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  access_token text NOT NULL,
  github_username text,
  github_user_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  github_id text,
  username text,
  name text,
  email text,
  avatar_url text,
  is_active boolean DEFAULT true,
  connected_at timestamp with time zone DEFAULT now(),
  CONSTRAINT github_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT github_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.gmail_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  auto_reply_personal boolean DEFAULT true,
  auto_reply_important_only boolean DEFAULT true,
  allowed_domains ARRAY DEFAULT ARRAY['gmail.com'::text, 'outlook.com'::text, 'yahoo.com'::text],
  blocked_domains ARRAY DEFAULT ARRAY[]::text[],
  newsletter_mode boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  auto_reply_enabled boolean DEFAULT true,
  auto_reply_filter text,
  auto_reply_allowed_senders ARRAY DEFAULT ARRAY[]::text[],
  auto_reply_subject_keywords ARRAY DEFAULT ARRAY[]::text[],
  auto_reply_manager_emails jsonb DEFAULT '[]'::jsonb,
  auto_forward_github boolean DEFAULT false,
  manager_update_types jsonb DEFAULT '["commits", "pr_updates"]'::jsonb,
  reply_mode text DEFAULT 'professional'::text,
  personal_only boolean DEFAULT true,
  ignore_corporate boolean DEFAULT true,
  enforce_whitelist boolean DEFAULT false,
  monitoring_enabled boolean DEFAULT false,
  custom_system_prompt text,
  CONSTRAINT gmail_configs_pkey PRIMARY KEY (id),
  CONSTRAINT gmail_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.gmail_domains (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  domain text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['allow'::text, 'block'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gmail_domains_pkey PRIMARY KEY (id),
  CONSTRAINT gmail_domains_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.gmail_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  email_address text NOT NULL,
  history_id text NOT NULL,
  message_id text,
  publish_time timestamp with time zone,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  error text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gmail_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT gmail_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.gmail_sent_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  message_id text NOT NULL,
  thread_id text,
  in_reply_to_id text,
  from_email text,
  to_email text,
  subject text,
  original_message text NOT NULL,
  sent_reply text NOT NULL,
  confidence_score double precision,
  was_escalated boolean DEFAULT false,
  escalation_id uuid,
  user_rating text CHECK (user_rating = ANY (ARRAY['good'::text, 'bad'::text])),
  rated_at timestamp with time zone,
  response_embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  chat_id text,
  CONSTRAINT gmail_sent_messages_pkey PRIMARY KEY (id),
  CONSTRAINT gmail_sent_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT gmail_sent_messages_escalation_id_fkey FOREIGN KEY (escalation_id) REFERENCES public.escalations(id)
);
CREATE TABLE public.gmail_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  refresh_token text,
  email_address text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  access_token text,
  gmail_id text,
  is_active boolean DEFAULT true,
  connected_at timestamp with time zone DEFAULT now(),
  email text,
  token_expires_at double precision,
  use_perplexity_for_low_confidence boolean DEFAULT false,
  watch_history_id text,
  watch_expiration timestamp with time zone,
  CONSTRAINT gmail_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT gmail_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.gmail_threads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  thread_id text NOT NULL,
  subject text,
  from_address text NOT NULL,
  last_message_at timestamp with time zone,
  replied boolean DEFAULT false,
  labels ARRAY DEFAULT ARRAY[]::text[],
  created_at timestamp with time zone DEFAULT now(),
  auto_replied boolean DEFAULT false,
  confidence_score double precision,
  needs_review boolean DEFAULT false,
  fact_checked boolean DEFAULT false,
  reply_text text,
  reply_message_id text,
  replied_at timestamp with time zone,
  unread boolean DEFAULT true,
  CONSTRAINT gmail_threads_pkey PRIMARY KEY (id),
  CONSTRAINT gmail_threads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.gmail_triage_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  condition_type text NOT NULL,
  condition_value text NOT NULL,
  action text NOT NULL,
  action_data jsonb DEFAULT '{}'::jsonb,
  priority integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gmail_triage_rules_pkey PRIMARY KEY (id),
  CONSTRAINT gmail_triage_rules_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.knowledge_constraints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  target_platform character varying NOT NULL,
  allowed_source_platforms ARRAY NOT NULL DEFAULT '{}'::text[],
  is_enabled boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT knowledge_constraints_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_constraints_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.knowledge_facts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  fact_text text NOT NULL,
  fact_type text NOT NULL,
  source text NOT NULL,
  source_url text,
  embedding USER-DEFINED,
  confidence double precision DEFAULT 1.0,
  valid_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT knowledge_facts_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_facts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.memories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  memory_type character varying NOT NULL DEFAULT 'fact'::character varying,
  content text NOT NULL,
  embedding USER-DEFINED,
  valid_from timestamp with time zone NOT NULL DEFAULT now(),
  valid_until timestamp with time zone,
  is_latest boolean NOT NULL DEFAULT true,
  stability double precision NOT NULL DEFAULT 1.0,
  difficulty double precision NOT NULL DEFAULT 0.3,
  retrievability double precision NOT NULL DEFAULT 1.0,
  last_accessed timestamp with time zone NOT NULL DEFAULT now(),
  access_count integer NOT NULL DEFAULT 0,
  source_platform character varying,
  source_id character varying,
  confidence double precision NOT NULL DEFAULT 1.0,
  extra_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  content_fts tsvector,
  event_time timestamp with time zone,
  CONSTRAINT memories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.memory_relations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_memory_id uuid NOT NULL,
  target_memory_id uuid NOT NULL,
  relation_type character varying NOT NULL,
  confidence double precision NOT NULL DEFAULT 1.0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT memory_relations_pkey PRIMARY KEY (id),
  CONSTRAINT memory_relations_source_memory_id_fkey FOREIGN KEY (source_memory_id) REFERENCES public.memories(id),
  CONSTRAINT memory_relations_target_memory_id_fkey FOREIGN KEY (target_memory_id) REFERENCES public.memories(id)
);
CREATE TABLE public.message_embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  message text NOT NULL,
  embedding USER-DEFINED,
  platform text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT message_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT message_embeddings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.migration_log (
  id integer NOT NULL DEFAULT nextval('migration_log_id_seq'::regclass),
  step text NOT NULL,
  status text NOT NULL,
  details text,
  timestamp timestamp with time zone DEFAULT now(),
  CONSTRAINT migration_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.perplexity_queries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  query text NOT NULL,
  response text,
  sources jsonb DEFAULT '[]'::jsonb,
  tokens_used integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT perplexity_queries_pkey PRIMARY KEY (id),
  CONSTRAINT perplexity_queries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.processed_webhooks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  webhook_id text NOT NULL UNIQUE,
  event_type text NOT NULL,
  user_id uuid,
  processed_at timestamp with time zone DEFAULT now(),
  status text NOT NULL,
  error_message text,
  event_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT processed_webhooks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reddit_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  post_mode text DEFAULT 'rant'::text,
  auto_reply_mentions boolean DEFAULT true,
  subscribed_subreddits ARRAY DEFAULT ARRAY[]::text[],
  post_subreddits ARRAY DEFAULT ARRAY[]::text[],
  post_schedule jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  use_perplexity_for_low_confidence boolean DEFAULT false,
  reply_mode text DEFAULT 'casual'::text,
  search_enabled boolean DEFAULT true,
  max_thread_length integer DEFAULT 5,
  monitoring_enabled boolean DEFAULT false,
  custom_system_prompt text,
  CONSTRAINT reddit_configs_pkey PRIMARY KEY (id),
  CONSTRAINT reddit_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.reddit_mentions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  comment_id text NOT NULL,
  post_id text NOT NULL,
  author text NOT NULL,
  subreddit text NOT NULL,
  text text NOT NULL,
  replied boolean DEFAULT false,
  reply_comment_id text,
  created_at timestamp with time zone DEFAULT now(),
  mention_id text,
  author_username text,
  body text,
  permalink text,
  reply_text text,
  replied_at timestamp with time zone,
  confidence_score double precision,
  needs_review boolean DEFAULT false,
  fact_checked boolean DEFAULT false,
  search_required boolean DEFAULT false,
  processing boolean DEFAULT false,
  CONSTRAINT reddit_mentions_pkey PRIMARY KEY (id),
  CONSTRAINT reddit_mentions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.reddit_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  post_id text NOT NULL,
  subreddit text NOT NULL,
  title text NOT NULL,
  content text,
  url text,
  score integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  post_type text DEFAULT 'text'::text,
  permalink text,
  CONSTRAINT reddit_posts_pkey PRIMARY KEY (id),
  CONSTRAINT reddit_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.reddit_sent_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  message_id text NOT NULL,
  thread_id text,
  parent_id text,
  subreddit text,
  original_message text NOT NULL,
  sent_reply text NOT NULL,
  confidence_score double precision,
  was_escalated boolean DEFAULT false,
  escalation_id uuid,
  user_rating text CHECK (user_rating = ANY (ARRAY['good'::text, 'bad'::text])),
  rated_at timestamp with time zone,
  response_embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  chat_id text,
  CONSTRAINT reddit_sent_messages_pkey PRIMARY KEY (id),
  CONSTRAINT reddit_sent_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT reddit_sent_messages_escalation_id_fkey FOREIGN KEY (escalation_id) REFERENCES public.escalations(id)
);
CREATE TABLE public.reddit_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  refresh_token text,
  reddit_username text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reddit_id text,
  username text,
  karma integer DEFAULT 0,
  is_active boolean DEFAULT true,
  connected_at timestamp with time zone DEFAULT now(),
  password_encrypted text,
  CONSTRAINT reddit_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT reddit_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.reddit_subreddits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  allow_rant boolean DEFAULT true,
  allow_showcase boolean DEFAULT true,
  auto_post boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reddit_subreddits_pkey PRIMARY KEY (id),
  CONSTRAINT reddit_subreddits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.sent_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['twitter'::text, 'reddit'::text, 'gmail'::text, 'telegram'::text])),
  message_id text NOT NULL,
  chat_id text,
  original_message text NOT NULL,
  sent_reply text NOT NULL,
  confidence_score double precision,
  was_escalated boolean DEFAULT false,
  escalation_id uuid,
  user_rating text CHECK (user_rating = ANY (ARRAY['good'::text, 'bad'::text])),
  rated_at timestamp with time zone,
  response_embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  chat_type text,
  chat_title text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sent_messages_pkey PRIMARY KEY (id),
  CONSTRAINT sent_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT sent_messages_escalation_id_fkey FOREIGN KEY (escalation_id) REFERENCES public.escalations(id)
);
CREATE TABLE public.slack_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  platform_enabled boolean DEFAULT true,
  auto_reply_enabled boolean DEFAULT false,
  platform_style_mode text DEFAULT 'default'::text,
  platform_delay_seconds integer DEFAULT 5,
  user_token text,
  bot_token text,
  team_id text,
  team_name text,
  user_slack_id text,
  channel_configs jsonb DEFAULT '{}'::jsonb,
  dm_configs jsonb DEFAULT '{}'::jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  connected_at timestamp without time zone,
  reply_in_thread boolean DEFAULT true,
  monitoring_enabled boolean DEFAULT false,
  custom_system_prompt text,
  CONSTRAINT slack_configs_pkey PRIMARY KEY (id),
  CONSTRAINT slack_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.slack_escalations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  channel_id text NOT NULL,
  channel_name text,
  channel_type text,
  message_ts text NOT NULL,
  thread_ts text,
  original_message text NOT NULL,
  suggested_reply text NOT NULL,
  confidence_score double precision,
  escalation_reason text,
  approved boolean,
  reviewed_at timestamp without time zone,
  reviewed_reply text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT slack_escalations_pkey PRIMARY KEY (id),
  CONSTRAINT slack_escalations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.slack_github_repo_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  repo_name text NOT NULL,
  summarize_enabled boolean DEFAULT false,
  target_channels ARRAY DEFAULT '{}'::text[],
  target_dms ARRAY DEFAULT '{}'::text[],
  action_types ARRAY DEFAULT '{commit,push,merge}'::text[],
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  notification_delay_seconds integer DEFAULT 0 CHECK (notification_delay_seconds >= 0 AND notification_delay_seconds <= 3600),
  CONSTRAINT slack_github_repo_configs_pkey PRIMARY KEY (id),
  CONSTRAINT slack_github_repo_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.slack_github_summary_escalations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  repo_name text NOT NULL,
  sync_timestamp timestamp without time zone NOT NULL,
  suggested_summary text NOT NULL,
  actions_captured jsonb,
  num_commits integer DEFAULT 0,
  target_channels ARRAY,
  target_dms ARRAY,
  confidence_score double precision,
  similarity_to_previous double precision,
  escalation_reason text,
  approved boolean,
  reviewed_at timestamp without time zone,
  reviewed_summary text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT slack_github_summary_escalations_pkey PRIMARY KEY (id),
  CONSTRAINT slack_github_summary_escalations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.slack_sent_github_summary (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  repo_name text NOT NULL,
  sync_timestamp timestamp without time zone NOT NULL,
  summary_text text NOT NULL,
  actions_captured jsonb,
  num_commits integer DEFAULT 0,
  num_pushes integer DEFAULT 0,
  num_merges integer DEFAULT 0,
  sent_to_channels ARRAY,
  sent_to_dms ARRAY,
  message_ts text,
  confidence_score double precision,
  similarity_to_previous double precision,
  rating text CHECK (rating = ANY (ARRAY['good'::text, 'bad'::text, NULL::text])),
  rated_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT slack_sent_github_summary_pkey PRIMARY KEY (id),
  CONSTRAINT slack_sent_github_summary_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.slack_sent_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  channel_id text NOT NULL,
  ts text NOT NULL,
  thread_ts text,
  original_message text NOT NULL,
  sent_reply text NOT NULL,
  platform text DEFAULT 'slack'::text,
  chat_id text,
  channel_type text,
  confidence_score double precision,
  style_mode text,
  user_rating text CHECK (user_rating = ANY (ARRAY['good'::text, 'bad'::text, NULL::text])),
  rated_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  message_id text,
  was_escalated boolean DEFAULT false,
  escalation_id uuid,
  response_embedding USER-DEFINED,
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT slack_sent_messages_pkey PRIMARY KEY (id),
  CONSTRAINT slack_sent_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT slack_sent_messages_escalation_id_fkey FOREIGN KEY (escalation_id) REFERENCES public.escalations(id)
);
CREATE TABLE public.sociomemory_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sociomemory_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT sociomemory_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.sociomemory_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])),
  content text NOT NULL,
  memory_context jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sociomemory_messages_pkey PRIMARY KEY (id),
  CONSTRAINT sociomemory_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.sociomemory_conversations(id)
);
CREATE TABLE public.subscription_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id text NOT NULL UNIQUE,
  product_name text NOT NULL,
  description text,
  subscription_tier text NOT NULL CHECK (subscription_tier = ANY (ARRAY['free'::text, 'pro'::text, 'enterprise'::text])),
  price_cents integer NOT NULL,
  currency text DEFAULT 'USD'::text,
  billing_interval text NOT NULL CHECK (billing_interval = ANY (ARRAY['monthly'::text, 'yearly'::text])),
  monthly_max_usage numeric NOT NULL DEFAULT 3.00,
  is_active boolean DEFAULT true,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT subscription_products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.telegram_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  session_string text NOT NULL,
  phone_number text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  custom_system_prompt text,
  CONSTRAINT telegram_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT telegram_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.token_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  platform text NOT NULL,
  operation text NOT NULL,
  input_tokens integer NOT NULL DEFAULT 0,
  output_tokens integer NOT NULL DEFAULT 0,
  total_tokens integer NOT NULL DEFAULT 0 CHECK (total_tokens >= 0),
  model text NOT NULL,
  cost_usd numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT token_usage_pkey PRIMARY KEY (id),
  CONSTRAINT token_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.twitter_bookmarks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  tweet_id text NOT NULL,
  tweet_text text,
  author_username text,
  bookmarked_at timestamp with time zone DEFAULT now(),
  author_name text,
  text text,
  tweet_created_at timestamp with time zone,
  CONSTRAINT twitter_bookmarks_pkey PRIMARY KEY (id),
  CONSTRAINT twitter_bookmarks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.twitter_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  auto_reply_mentions boolean DEFAULT true,
  auto_like_bookmarks boolean DEFAULT false,
  auto_retweet_niche boolean DEFAULT false,
  post_schedule jsonb DEFAULT '[]'::jsonb,
  monitored_hashtags ARRAY DEFAULT ARRAY[]::text[],
  niche_keywords ARRAY DEFAULT ARRAY[]::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  reply_mode text DEFAULT 'casual'::text,
  bookmark_sync_enabled boolean DEFAULT false,
  use_perplexity_for_low_confidence boolean DEFAULT false,
  monitoring_enabled boolean DEFAULT false,
  max_thread_length integer DEFAULT 5,
  search_enabled boolean DEFAULT true,
  last_mention_id text,
  custom_system_prompt text,
  CONSTRAINT twitter_configs_pkey PRIMARY KEY (id),
  CONSTRAINT twitter_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.twitter_mentions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  tweet_id text NOT NULL,
  author_id text NOT NULL,
  author_username text,
  text text NOT NULL,
  replied boolean DEFAULT false,
  reply_tweet_id text,
  created_at timestamp with time zone DEFAULT now(),
  author_name text,
  conversation_id text,
  reply_text text,
  replied_at timestamp with time zone,
  confidence_score double precision,
  needs_review boolean DEFAULT false,
  fact_checked boolean DEFAULT false,
  CONSTRAINT twitter_mentions_pkey PRIMARY KEY (id),
  CONSTRAINT twitter_mentions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.twitter_sent_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  message_id text NOT NULL,
  conversation_id text,
  in_reply_to_id text,
  mentioned_username text,
  original_message text NOT NULL,
  sent_reply text NOT NULL,
  confidence_score double precision,
  was_escalated boolean DEFAULT false,
  escalation_id uuid,
  user_rating text CHECK (user_rating = ANY (ARRAY['good'::text, 'bad'::text])),
  rated_at timestamp with time zone,
  response_embedding USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  chat_id text,
  CONSTRAINT twitter_sent_messages_pkey PRIMARY KEY (id),
  CONSTRAINT twitter_sent_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT twitter_sent_messages_escalation_id_fkey FOREIGN KEY (escalation_id) REFERENCES public.escalations(id)
);
CREATE TABLE public.twitter_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  access_token text NOT NULL,
  access_token_secret text,
  twitter_user_id text,
  twitter_username text,
  twitter_name text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  connected_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  refresh_token text,
  twitter_id text,
  username text,
  name text,
  profile_image_url text,
  token_expires_at double precision,
  CONSTRAINT twitter_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT twitter_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.unified_embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  content text NOT NULL,
  embedding USER-DEFINED,
  platform text NOT NULL,
  source_type text NOT NULL,
  source_id text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT unified_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT unified_embeddings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  platform text NOT NULL,
  action_type text NOT NULL,
  tokens_used integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  enable_notifications boolean DEFAULT true,
  response_style text DEFAULT 'casual'::text,
  auto_reply_delay integer DEFAULT 5,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  ignore_confidence boolean DEFAULT false,
  use_perplexity_for_low_confidence boolean DEFAULT false,
  dark_mode boolean DEFAULT true,
  ai_provider text DEFAULT 'default'::text CHECK (ai_provider = ANY (ARRAY['default'::text, 'gemini'::text, 'claude'::text])),
  custom_ai_api_key text,
  CONSTRAINT user_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  email text NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  subscription_tier text DEFAULT 'free'::text,
  credits integer DEFAULT 100,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  twitter_connected boolean DEFAULT false,
  reddit_connected boolean DEFAULT false,
  gmail_connected boolean DEFAULT false,
  github_connected boolean DEFAULT false,
  preferences jsonb DEFAULT '{"auto_reply_enabled": true, "perplexity_enabled": true, "confidence_threshold": 0.7, "github_context_enabled": true}'::jsonb,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  subscription_tier text NOT NULL DEFAULT 'free'::text CHECK (subscription_tier = ANY (ARRAY['free'::text, 'pro'::text, 'enterprise'::text])),
  subscription_started_at timestamp with time zone,
  subscription_expires_at timestamp with time zone,
  monthly_max_usage numeric NOT NULL DEFAULT 3.0000,
  current_monthly_usage numeric NOT NULL DEFAULT 0.0000,
  last_reset_date date NOT NULL DEFAULT CURRENT_DATE,
  reset_day_of_month integer NOT NULL CHECK (reset_day_of_month >= 1 AND reset_day_of_month <= 28),
  total_lifetime_usage numeric NOT NULL DEFAULT 0.0000,
  total_requests integer NOT NULL DEFAULT 0,
  blocked_requests integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  subscribed_product_id text,
  CONSTRAINT user_usage_pkey PRIMARY KEY (id),
  CONSTRAINT user_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT user_usage_subscribed_product_id_fkey FOREIGN KEY (subscribed_product_id) REFERENCES public.subscription_products(product_id)
);